name: 'PixelLint'
description: 'AI-powered pixel-perfect design linting for screenshots'
author: 'Caboo Intelligence'

branding:
  icon: 'eye'
  color: 'purple'

inputs:
  pattern:
    description: 'Glob pattern for screenshot files'
    required: false
    default: '**/*.{png,jpg,jpeg}'
  threshold:
    description: 'Minimum score to pass (0-1)'
    required: false
    default: '0.7'
  fail-on-issues:
    description: 'Fail the action if issues found'
    required: false
    default: 'true'

outputs:
  score:
    description: 'Overall score (0-1)'
  grade:
    description: 'Letter grade'
  issues:
    description: 'Number of issues found'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pattern }}
    - ${{ inputs.threshold }}
    - ${{ inputs.fail-on-issues }}